services:
  mongo:
    image: mongo:7
    container_name: dizipay-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - dizipay_mongo:/data/db

  redis:
    image: redis:7-alpine
    container_name: dizipay-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - dizipay_redis:/data

volumes:
  dizipay_mongo:
  dizipay_redis:
